config/routes.rb
Rails.application.routes.draw do
  resources :comments
  resources :image_posts
  resources :text_posts
  resources :posts
  resources :users
  resources :sessions

  get 'signup', to: 'users#new', as: 'signup'
  get "follow/:id", to: 'users#follow', as: 'follow_user'

  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  root 'posts#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user

  validates :post_id, presence: true
  validates :user_id, presence: true
end

app/models/image_post.rb
class ImagePost < Post
	validates :url, presence: true
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
  has_many :comments, dependent: :destroy
  
  validates :user_id, presence: true
  validates :type, presence: true
end

app/models/subscription.rb
class Subscription < ActiveRecord::Base
  belongs_to :leader, class_name: 'User'
  belongs_to :follower, class_name: 'User'
end

app/models/text_post.rb
class TextPost < Post
	validates :body, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :subscriptions, foreign_key: :follower_id, dependent: :destroy
  has_many :leaders, through: :subscriptions

  has_many :reverse_subscriptions, foreign_key: :leader_id, class_name: 'Subscription', dependent: :destroy
  has_many :followers, through: :reverse_subscriptions

  has_many :posts, dependent: :destroy
  has_many :text_posts, dependent: :destroy
  has_many :image_posts, dependent: :destroy

  has_many :comments

  has_secure_password

  validates :email, presence: true, uniqueness: true

  def following?(leader)
    leaders.include? leader
  end

  def follow!(leader)
    if leader != self && !following?(leader)
      leaders << leader
    end
  end

  def timeline_user_ids
    leader_ids + [id]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def current_user
  	if session[:user_id]
  		@current_user ||= User.find(session[:user_id])
  	end
  end
  helper_method :current_user

  def authenticate_user!
  	redirect_to login_path unless current_user
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!

	def create
		@comment = current_user.comments.build(comment_params)

		if @comment.save
			redirect_to post_path(@comment.post_id), notice: 'Comment was successfully created.'
		else
			redirect_to post_path(@comment.post_id), alert: 'Error creating comment.'
		end
	end

	private

	def comment_params
		params.require(:comment).permit(:body, :post_id)
	end

end

app/controllers/image_posts_controller.rb
class ImagePostsController < ApplicationController

	def new
		@image_post = ImagePost.new
	end

	def create
		@image_post = current_user.image_posts.build(image_post_params)
		if @image_post.save
			redirect_to post_path(@image_post), notice: "Post created!"
		else
			render :new, alert: "Error creating post."
		end
	end

	private

	def image_post_params
		params.require(:image_post).permit(:title, :url, :body)
	end
	
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :authenticate_user!

	def index
		user_ids = current_user.timeline_user_ids
		#@posts = Post.where(user_id: user_ids).order("created_at DESC")
		@posts = Post.includes(:user).where(user_id: user_ids).order("created_at DESC")
	end

	def show
		@post = Post.find(params[:id])
	end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	
	def new
	end

	def create
		user = User.find_by(email: params[:email])
		if user && user.authenticate(params[:password])
			session[:user_id] = user.id
			redirect_to root_url, notice: "Log in successful!"
		else
			flash.now.alert = "Invalid email or password"
			render "new"
		end
	end

	def destroy
		session[:user_id] = nil
		redirect_to root_url, notice: "Log out successful!"
	end

end

app/controllers/text_posts_controller.rb
class TextPostsController < ApplicationController
	def new
		@text_post = TextPost.new
	end

	def create
		@text_post = current_user.text_posts.build(text_post_params)

		if @text_post.save
			redirect_to post_path(@text_post), notice: "Post created!"
		else
			render :new, alert: "Error creating post"
		end
	end

	private

	def text_post_params
		params.require(:text_post).permit(:title, :body)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :authenticate_user!, only: :follow

	def new
		@user = User.new
	end

	def create
		@user = User.new(user_params)
		if @user.save
			redirect_to root_url, notice: "Welcome to the site!"
		else
			render "new"
		end
	end

	def show
		@user = User.find(params[:id])
		@posts = @user.posts.order("created_at DESC")
	end

	def follow
		@user = User.find(params[:id])
		if current_user.follow!(@user)
			redirect_to @user, notice: "Follow successful!"
		else
			redirect_to @user, alert: "Error following"
		end
	end

	private

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/image_posts_helper.rb
module ImagePostsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/text_posts_helper.rb
module TextPostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/comments/_comment.html.erb
<p><em><%= comment.user.name %> said:</em></p>
<p><%= comment.body %></p>

app/views/image_posts/_form.html.erb
<%= form_for @image_post do |f| %>
	<div class="form-group">
		<%= f.label :title %>
		<%= f.text_field :title, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :url %>
		<%= f.text_field :url, class: "form-control" %>
	</div>
	<div class="form-group">
		<%= f.label :body %>
		<%= f.text_area :body, class: "form-control" %>
	</div>

	<%= f.submit class: "btn btn-primary" %>
	<%= link_to 'Cancel', :back, class: "btn btn-default" %>
	<% end %>

app/views/image_posts/_image_post.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
			<%= image_post.title %>
		</h3>
		<%= link_to "#{time_ago_in_words image_post.created_at} ago", post_path(image_post) %>
	</div>

	<div class="panel-body">
		<p><em>By <%= link_to image_post.user.name, image_post.user %></em></p>

		<%= image_tag image_post.url, class: "img-responsive" %>

		<%= image_post.body %>
	</div>
</div>

app/views/image_posts/new.html.erb
<div class="page-header">
	<h1>New Image Post</h1>
</div>

<%= render 'form' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Social</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<div class="container">
		<% if notice %>
		  <div class="alert alert-success"><%= notice %></div>
		<% end %>
		<% if alert %>
		  <div class="alert alert-danger"><%= alert %></div>
		<% end %>

		<div class="pull-right">
			<% if current_user %>
				<%= link_to 'Profile', current_user %>
			  <%= link_to 'Log Out', logout_path %>
			<% else %>
			  <%= link_to 'Log In', login_path %> or
			  <%= link_to 'Sign Up', signup_path %>
			<% end %>
		</div>
		
		<%= yield %>
	</div>

</body>
</html>

app/views/posts/index.html.erb
<div class="page-header">
	<h1>Home</h1>
</div>

<p>
	<%= link_to "New Text Post", new_text_post_path, class: "btn btn-default" %>
	<%= link_to "New Image Post", new_image_post_path, class: "btn btn-default" %>
</p>

<%= render @posts %>

app/views/posts/show.html.erb
<div class="page-header">
	<h1>Post</h1>
</div>

<%= render @post %>

<h3>Comments</h3>

<%= render @post.comments %>

<h4>New Comment</h4>
<%= form_for @post.comments.build do |f| %>
  <div class="form-group">
  	<%= f.label :body %><br>
  	<%= f.text_area :body, class: "form-control" %>
  </div>
  <%= f.hidden_field :post_id %>
  <%= f.submit class: "btn btn-primary" %>
  <% end %>

<%= link_to "Home", posts_path, class: "btn btn-default" %>

app/views/text_posts/_form.html.erb
<%= form_for @text_post do |f| %>
  <div class="form-group">
  	<%= f.label :title %>
  	<%= f.text_field :title, class: "form-control" %>
  </div>
  <div class="form-group">
  	<%= f.label :body %>
  	<%= f.text_area :body, class: "form-control" %>
  </div>

  <%= f.submit class: "btn btn-primary" %>
  <%= link_to 'Cancel', :back, class: "btn btn-default" %>
  <% end %>

app/views/text_posts/_text_post.html.erb
<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title">
			<%= text_post.title %>
		</h3>
		<%= link_to("#{time_ago_in_words text_post.created_at} ago", post_path(text_post)) %>
	</div>

	<div class="panel-body">
		<p><em>By <%= link_to text_post.user.name, text_post.user %></em></p>

		<%= text_post.body %>
	</div>
</div>

app/views/text_posts/new.html.erb
<div class="page-header">
	<h1>New Text Post</h1>
</div>

<%= render 'form' %>

app/views/users/new.html.erb
<div class="page-header">
	<h1>Sign Up</h1>
</div>

<%= form_for(@user) do |f| %>
	<% if @user.errors.any? %>
	  <div class="alert alert-danger">
	  	<strong>
	  		<%= pluralize(@user.errors.count, "error") %> prevented you from siging up:
	  	</strong>
	  	<ul>
	  		<% @user.errors.full_messages.each do |msg| %>
	  		  <li><%= msg %></li>
	  		  <% end %>
	  	</ul>
	  </div>
	 <% end %>

	 <div class="form-group">
	 	<%= f.label :email %>
	 	<%= f.email_field :email, class: "form-control" %>
	 </div>
	 <div class="form-group">
	 	<%= f.label :password %>
	 	<%= f.password_field :password, class: "form-control" %>
	 </div>
	 <div class="form-group">
	 	<%= f.label :password_confirmation %>
	 	<%= f.password_field :password_confirmation, class: "form-control" %>
	 </div>

	 <%= f.submit class: "btn btn-primary" %>
	 <% end %>

app/views/users/show.html.erb
<div class="page-header">
	<h1>User</h1>
</div>

<p class="lead"><%= @user.name %></p>

<% if current_user %>
	<% if current_user != @user && !current_user.following?(@user) %>
		<%= link_to "Follow", follow_user_path(@user), class: "btn btn-default" %>
		<% end %>
	<% end %>

<h2>Posts</h2>

<%= render @posts %>

<%= link_to "Home", root_path, class: "btn btn-default" %>